"""create tickets table

Revision ID: 9c4e455d5a28
Revises: 6cf6b8b043e0
Create Date: 2026-08-10 21:08:27.959119

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9c4e455d5a28"
down_revision: str | Sequence[str] | None = "6cf6b8b043e0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tickets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("open", "in_progress", "resolved", "closed", name="ticket_status"),
            server_default="open",
            nullable=False,
        ),
        sa.Column(
            "priority",
            sa.Enum("low", "medium", "high", "urgent", name="ticket_priority"),
            server_default="medium",
            nullable=False,
        ),
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("assignee_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["assignee_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["customer_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tickets_assignee_id"), "tickets", ["assignee_id"], unique=False
    )
    op.create_index(
        op.f("ix_tickets_customer_id"), "tickets", ["customer_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(
        op.f("ix_tickets_customer_id"),
        table_name="tickets",
    )
    op.drop_index(
        op.f("ix_tickets_assignee_id"),
        table_name="tickets",
    )
    op.drop_table("tickets")

    sa.Enum(
        name="ticket_priority",
    ).drop(
        op.get_bind(),
        checkfirst=True,
    )
    sa.Enum(
        name="ticket_status",
    ).drop(
        op.get_bind(),
        checkfirst=True,
    )
